server:
  applicationConnectors:
    - type: http
      port: 5000
db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/marquez
  user: marquez
  password: marquez
metrics:
  reporters:
    - type: console
jobService:
  enabled: true