version: '3.8'

services:
  webserver:
    build:
      context: ./webserver
    ports:
      - "7237:7237"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  marquez-db:
    image: postgres:14
    container_name: marquez-db
    environment:
      - POSTGRES_DB=${MARQUEZ_DB_NAME}
      - POSTGRES_USER=${MARQUEZ_DB_USER}
      - POSTGRES_PASSWORD=${MARQUEZ_DB_PASSWORD}
    volumes:
      - marquez_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MARQUEZ_DB_USER:-marquez}"]
      interval: 10s
      timeout: 5s
      retries: 5

  marquez-api:
    image: "marquezproject/marquez:0.47.0"
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=${MARQUEZ_PORT}
      - MARQUEZ_ADMIN_PORT=${MARQUEZ_ADMIN_PORT}
      - MARQUEZ_DB_HOST=${MARQUEZ_DB_HOST}
      - MARQUEZ_DB_PORT=${MARQUEZ_PORT}"
      - MARQUEZ_DB_NAME=${MARQUEZ_DB_NAME}
      - MARQUEZ_DB_USER=${MARQUEZ_DB_USER}
      - MARQUEZ_DB_PASSWORD=${MARQUEZ_DB_PASSWORD}
    ports:
      - "${MARQUEZ_PORT}:${MARQUEZ_PORT}"
      - "${MARQUEZ_ADMIN_PORT}:${MARQUEZ_ADMIN_PORT}"
    depends_on:
      marquez-db:
        condition: service_healthy

  marquez-web:
    image: "marquezproject/marquez-web:0.46.0"
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=${MARQUEZ_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - marquez-api

volumes:
  marquez_postgres_data:
  postgres_data:
