aws:
  region: us-east-1
  s3_bucket: storage-bucket-example
emr:
  release_label: emr-6.4.0
  applications:
    - Spark
    - Hadoop
  scripts_s3_path: s3://storage-bucket-example/emr-scripts/
lineage:
  marquez_url: http://marquez:5000
database:
  host: your-rds-endpoint
  port: 5432
  name: stock_data
  user: dbuser
  password: dbpassword
alpha_vantage:
  api_key: your-alpha-vantage-api-key