version: '3.7'
services:
  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
    environment:
      MARQUEZ_CONFIG: /app/config/marquez.yml
    volumes:
      - ./config/marquez.yml:/app/config/marquez.yml